# Generated by Django 6.0.6 on 2026-06-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_admin',
            name='role',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
