# Generated by Django 6.0.6 on 2026-06-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0002_tbl_admin_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tbl_Admin',
        ),
    ]
