# Generated by Django 6.0.6 on 2026-06-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0004_photofolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofolder',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
