# Generated by Django 6.0.6 on 2026-06-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0005_alter_photofolder_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='folder_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pizxifyapp.photofolder')),
            ],
        ),
    ]
