# Generated by Django 6.0.6 on 2026-06-20 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0006_folderphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizxifyapp.folderphoto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizxifyapp.userregister')),
            ],
            options={
                'unique_together': {('photo', 'user')},
            },
        ),
    ]
