# Generated by Django 6.0.6 on 2026-06-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0007_photolike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('photos_per_page', models.JSONField(default=dict)),
                ('photo_ids', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizxifyapp.userregister')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizxifyapp.photofolder')),
            ],
        ),
    ]
