# Generated by Django 6.0.6 on 2026-06-20 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0008_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('collage', models.ImageField(upload_to='album_pages/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pizxifyapp.album')),
            ],
        ),
    ]
