# Generated by Django 6.0.6 on 2026-06-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0009_albumpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('position', models.IntegerField(default=0)),
                ('rotation', models.IntegerField(default=0)),
                ('crop_x', models.FloatField(default=0)),
                ('crop_y', models.FloatField(default=0)),
                ('crop_width', models.FloatField(default=0)),
                ('crop_height', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_photos', to='pizxifyapp.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizxifyapp.folderphoto')),
            ],
            options={
                'ordering': ['page_number', 'position'],
            },
        ),
    ]
