# Generated by Django 6.0.5 on 2026-06-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0010_albumphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphoto',
            name='edited_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_edited/'),
        ),
    ]
