# Generated by Django 6.0.5 on 2026-06-23 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0011_albumphoto_edited_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphoto',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
