# Generated by Django 6.0.6 on 2026-06-24 07:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0012_albumphoto_share_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumphoto',
            name='share_token',
        ),
        migrations.AddField(
            model_name='album',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
