# Generated by Django 6.0.6 on 2026-06-26 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0013_remove_albumphoto_share_token_album_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerPhotoFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_folders', to='pizxifyapp.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerFolderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='folder_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancephotos', to='pizxifyapp.freelancerphotofolder')),
            ],
        ),
    ]
