# Generated by Django 6.0.6 on 2026-06-26 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizxifyapp', '0014_freelancerphotofolder_freelancerfolderphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerfolderphoto',
            name='image',
            field=models.ImageField(upload_to='freelance_folder_photos/'),
        ),
        migrations.CreateModel(
            name='FreelancerAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('photos_per_page', models.JSONField(default=dict)),
                ('photo_ids', models.TextField()),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizxifyapp.userregister')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizxifyapp.freelancerphotofolder')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerAlbumPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('collage', models.ImageField(upload_to='freelance_album_pages/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pizxifyapp.freelanceralbum')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerAlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('position', models.IntegerField(default=0)),
                ('rotation', models.IntegerField(default=0)),
                ('crop_x', models.FloatField(default=0)),
                ('crop_y', models.FloatField(default=0)),
                ('crop_width', models.FloatField(default=0)),
                ('crop_height', models.FloatField(default=0)),
                ('edited_image', models.ImageField(blank=True, null=True, upload_to='freelance_album_edited/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_album_photos', to='pizxifyapp.freelanceralbum')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizxifyapp.freelancerfolderphoto')),
            ],
            options={
                'ordering': ['page_number', 'position'],
            },
        ),
    ]
